### PR TITLE
Feature/rejections

### LINKED ISSUE #65: Backend Rejections
Upon login of a rejected user, they’ll have a banner alert telling them they’ve been rejected. They should have the ability to click on some text/button from within the banner alert to trigger a ‘protest’ to the admin side of things.

image

Backend needs to be able to handle rejections

### PR DESCRIPTION
**Pull request by jedrm**
# Rejections

- Resolves #65 
- There is a new endpoint for creating a protest
- There is a new endpoint for rejecting a user
- New fields to `user` has been added: `rejected` and `protested`
- Admin panel for protests have been set up
- The documentation for the new endpoints have been updated in the Notion

### CODE REVIEW

**Comment by ShehabMohsen** [comment]
maybe we should let @thedreamfish work on the frontend portion before merging with main 🤔

**Comment by jedrm** [comment]
> maybe we should let @thedreamfish work on the frontend portion before merging with main thinking

Agreed. I have made drafted the PR for now so we can finalize rejections in the site.

**Comment by thedreamfish** [comment]
> maybe we should let @thedreamfish work on the frontend portion before merging with main 🤔
done

**Review by ShehabMohsen — APPROVED** [review]
LGTM, so proud of you guys 🤧

**Pull request merged**
